/* eslint-disable @next/next/no-img-element */
import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";

// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay, Pagination, Navigation } from "swiper";

// Components
import ProductSwiper from "../components/Product/ProductSwiper";
import { Tabs, TabList, Tab, TabPanels, TabPanel } from "../components/global";

import { Button } from "flowbite-react";

import products from "../../data";

const brandLogos = [
  "/assets/images/BrandLogos/acer.webp",
  "/assets/images/BrandLogos/amd.webp",
  "/assets/images/BrandLogos/brother.webp",
  "/assets/images/BrandLogos/canon.webp",
  "/assets/images/BrandLogos/dell.webp",
  "/assets/images/BrandLogos/dlink.webp",
  "/assets/images/BrandLogos/epson.webp",
  "/assets/images/BrandLogos/gigabyte.webp",
  "/assets/images/BrandLogos/hp.webp",
  "/assets/images/BrandLogos/huawei.webp",
  "/assets/images/BrandLogos/intel.webp",
  "/assets/images/BrandLogos/kingston.webp",
  "/assets/images/BrandLogos/logitech.webp",
  "/assets/images/BrandLogos/microsoft.webp",
  "/assets/images/BrandLogos/msi.webp",
];

const bannerImg = [
  "/assets/images/Banners/Banner1.jpg",
  "/assets/images/Banners/Banner2.jpg",
  "/assets/images/Banners/Banner3.jpg",
  "/assets/images/Banners/Banner4.jpg",
  "/assets/images/Banners/Banner5.jpg",
  "/assets/images/Banners/Banner6.jpg",
];

export default function Home() {
  const [openTab, setOpenTab] = useState(1);
  const [openTab2, setOpenTab2] = useState(1);

  return (
    <div>
      <Head>
        <title>PC Link | PC Builder and Accessories</title>
        <meta name="description" content="Generated by Mike van Peeren" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Swiper
          spaceBetween={30}
          centeredSlides={true}
          autoplay={{
            delay: 2500,
            disableOnInteraction: false,
          }}
          navigation={true}
          modules={[Autoplay, Pagination, Navigation]}
          className="mySwiper"
        >
          {bannerImg.map((img, i) => {
            return (
              <SwiperSlide key={i} className="select-none">
                <img src={img} alt="Banner" width="100%" />
              </SwiperSlide>
            );
          })}
        </Swiper>

        <div className="container relative mx-auto py-4">
          <Tabs>
            <TabList categoryName="Computers">
              <Tab index={1} active={openTab} setOpenTab={setOpenTab}>
                Desktop PC
              </Tab>
              <Tab index={2} active={openTab} setOpenTab={setOpenTab}>
                Notebooks
              </Tab>
              <Tab index={3} active={openTab} setOpenTab={setOpenTab}>
                Software
              </Tab>
            </TabList>
            <TabPanels>
              <TabPanel index={1} openTab={openTab}>
                <ProductSwiper products={products} />
              </TabPanel>
              <TabPanel index={2} openTab={openTab}>
                Notebooks asdasds
              </TabPanel>
              <TabPanel index={3} openTab={openTab}>
                <ProductSwiper products={products} />
              </TabPanel>
            </TabPanels>
          </Tabs>

          <Tabs>
            <TabList categoryName="Components">
              <Tab index={1} active={openTab2} setOpenTab={setOpenTab2}>
                Processor
              </Tab>
              <Tab index={2} active={openTab2} setOpenTab={setOpenTab2}>
                Motherboard
              </Tab>
              <Tab index={3} active={openTab2} setOpenTab={setOpenTab2}>
                Graphics Card
              </Tab>
              <Tab index={4} active={openTab2} setOpenTab={setOpenTab2}>
                Memory
              </Tab>
            </TabList>
            <TabPanels>
              <TabPanel index={1} openTab={openTab2}>
                <ProductSwiper products={products} />
              </TabPanel>
              <TabPanel index={2} openTab={openTab2}>
                Notebooks asdasds
                <Button gradientMonochrome="info">
                  Default
                </Button>
              </TabPanel>
              <TabPanel index={3} openTab={openTab2}>
                <ProductSwiper products={products} />
              </TabPanel>
              <TabPanel index={4} openTab={openTab2}>
                Memory
              </TabPanel>
            </TabPanels>
          </Tabs>
        </div>

        <div className="container relative mx-auto py-4">
          <Swiper
            slidesPerView={7}
            spaceBetween={50}
            slidesPerGroup={1}
            loop={true}
            loopFillGroupWithBlank={true}
            navigation={true}
            modules={[Pagination, Navigation]}
            style={{ height: "200px" }}
          >
            {brandLogos.map((logo, i) => {
              return (
                <SwiperSlide key={i} className="flex justify-center items-center select-none">
                  <Image priority width={100} height={100} src={logo} alt="logo" />
                </SwiperSlide>
              );
            })}
          </Swiper>
        </div>
      </div>
    </div>
  );
}
