/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";

// import { BsFillEyeFill } from "react-icons/bs";
// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";
// import required modules
import { Autoplay, Pagination, Navigation } from "swiper";

// import products from "../data";

// Components
// import Card from "../components/card";
import Tabs from "../components/Tabs";

// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

const brandLogos = [
  "/assets/images/BrandLogos/acer.webp",
  "/assets/images/BrandLogos/amd.webp",
  "/assets/images/BrandLogos/brother.webp",
  "/assets/images/BrandLogos/canon.webp",
  "/assets/images/BrandLogos/dell.webp",
  "/assets/images/BrandLogos/dlink.webp",
  "/assets/images/BrandLogos/epson.webp",
  "/assets/images/BrandLogos/gigabyte.webp",
  "/assets/images/BrandLogos/hp.webp",
  "/assets/images/BrandLogos/huawei.webp",
  "/assets/images/BrandLogos/intel.webp",
  "/assets/images/BrandLogos/kingston.webp",
  "/assets/images/BrandLogos/logitech.webp",
  "/assets/images/BrandLogos/microsoft.webp",
  "/assets/images/BrandLogos/msi.webp",
];

const bannerImg = [
  "/assets/images/Banners/Banner1.jpg",
  "/assets/images/Banners/Banner2.jpg",
  "/assets/images/Banners/Banner3.jpg",
  "/assets/images/Banners/Banner4.jpg",
  "/assets/images/Banners/Banner5.jpg",
  "/assets/images/Banners/Banner6.jpg",
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>PC Link | PC Builder and Accessories</title>
        <meta name="description" content="Generated by Mike van Peeren" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Swiper
          spaceBetween={30}
          centeredSlides={true}
          autoplay={{
            delay: 2500,
            disableOnInteraction: false,
          }}
          navigation={true}
          modules={[Autoplay, Pagination, Navigation]}
          className="mySwiper"
        >
          {bannerImg.map((img, i) => {
            return (
              <SwiperSlide key={i}>
                <img src={img} alt="Banner" width="100%" />
              </SwiperSlide>
            );
          })}
        </Swiper>

        <div className="container relative mx-auto py-4">
          <Tabs categoryName="Computers" list={["Desktop PC", "Notebooks", "Software"]} />
          <Tabs
            categoryName="Components"
            list={["Processor", "Motherboard", "Graphics Card", "Memory"]}
          />
        </div>

        <div className="container relative mx-auto py-4">
          <Swiper
            slidesPerView={7}
            spaceBetween={50}
            slidesPerGroup={1}
            loop={true}
            loopFillGroupWithBlank={true}
            navigation={true}
            modules={[Pagination, Navigation]}
            style={{ height: "200px" }}
          >
            {brandLogos.map((logo, i) => {
              return (
                <SwiperSlide key={i} className="flex justify-center items-center select-none">
                  <Image priority width={100} height={100} src={logo} alt="logo" />
                </SwiperSlide>
              );
            })}
          </Swiper>
        </div>
      </div>
    </div>
  );
}
